USE hr_db;

#1
SELECT EMPLOYEE_ID, REVERSE(SUBSTR(REVERSE(EMAIL),4,15))
FROM employees;

#2
SELECT * FROM locations
WHERE CHAR_LENGTH(STREET_ADDRESS) = (SELECT MIN(CHAR_LENGTH(STREET_ADDRESS)) FROM locations);

#3
SELECT FIRST_NAME AS Firstname, CHAR_LENGTH(FIRST_NAME) AS LengthOfFirstname
FROM employees
WHERE FIRST_NAME LIKE 'A%' OR FIRST_NAME LIKE 'J%' OR FIRST_NAME LIKE 'M%'
ORDER BY FIRST_NAME;