USE hr_db;

#1
SELECT FIRST_NAME, LAST_NAME, SALARY
FROM employees
WHERE SALARY >
(SELECT SALARY FROM employees WHERE LAST_NAME = 'Bull');
#SELECT LAST_NAME, SALARY FROM employees WHERE LAST_NAME = 'Bull';

#2
SELECT FIRST_NAME, LAST_NAME
FROM employees
WHERE DEPARTMENT_ID =
(SELECT DEPARTMENT_ID FROM departments WHERE DEPARTMENT_NAME = 'IT');
#SELECT DEPARTMENT_ID FROM departments WHERE DEPARTMENT_NAME = 'IT';
#SELECT FIRST_NAME, LAST_NAME FROM employees WHERE DEPARTMENT_ID = 60;

#3
SELECT FIRST_NAME, LAST_NAME
FROM employees
WHERE JOB_ID IN
(SELECT JOB_ID FROM jobs WHERE JOB_TITLE LIKE "%Manager%");

#4
SELECT FIRST_NAME, LAST_NAME, SALARY
FROM employees
WHERE SALARY >
(SELECT AVG(SALARY) FROM employees);
#SELECT AVG(SALARY) FROM employees;

#5
SELECT FIRST_NAME, LAST_NAME, SALARY
FROM employees
WHERE SALARY IN
(SELECT SALARY FROM jobs WHERE employees.SALARY = jobs.MIN_SALARY);

#6
SELECT employees.FIRST_NAME, employees.LAST_NAME, employees.SALARY
FROM employees NATURAL JOIN jobs
WHERE employees.SALARY = jobs.MIN_SALARY;

#7
SELECT employees.EMPLOYEE_ID, employees.FIRST_NAME, employees.LAST_NAME, departments.DEPARTMENT_NAME
FROM employees NATURAL JOIN departments
WHERE departments.DEPARTMENT_ID = employees.DEPARTMENT_ID;

#8
SELECT * FROM employees ORDER BY EMPLOYEE_ID DESC LIMIT 10;